cmake_minimum_required(VERSION 3.13 FATAL_ERROR)
project(GCLC LANGUAGES CXX)

include(GNUInstallDirs)

set(GCLC_APP_ID "io.github.ADG_Foundation.gclc")
set(gui AUTO CACHE STRING "build the GCLC GUI")
set_property(CACHE gui PROPERTY STRINGS AUTO ON OFF)

# enable -W and -Wall if possible
include(CheckCXXCompilerFlag)
CHECK_CXX_COMPILER_FLAG(-W HAS_W)
if(HAS_W)
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -W")
endif()
CHECK_CXX_COMPILER_FLAG(-Wall HAS_WALL)
if(HAS_WALL)
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wall")
endif()
CHECK_CXX_COMPILER_FLAG(-Wmissing-declarations HAS_WMISSING_DECLARATIONS)
if(HAS_WMISSING_DECLARATIONS)
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wmissing-declarations")
endif()
CHECK_CXX_COMPILER_FLAG(-Wcast-qual HAS_WCAST_QUAL)
if(HAS_WCAST_QUAL)
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wcast-qual")
endif()

if(NOT gui STREQUAL "OFF")
  find_package(Qt6 COMPONENTS Core Gui PrintSupport Widgets)
  if(gui STREQUAL "AUTO")
    if(Qt6_FOUND)
      message(STATUS "GUI mode: AUTO — Qt6 found, enabling GCLC GUI build (-Dgui=ON)")
      set(gui ON)
    else()
      message(STATUS "GUI mode: AUTO — Qt6 not found, skipping GCLC GUI build (-Dgui=OFF)")
      set(gui OFF)
    endif()
  elseif(NOT Qt6_FOUND)
    message(FATAL_ERROR "GUI mode: ON — Required Qt6 components (Core, Gui, PrintSupport, Widgets) were not found.")
  else()
    message(STATUS "GUI mode: ON — Qt6 found, building GCLC GUI")
  endif()
endif()

include(cli.cmake)

if(gui)
  include(gui.cmake)
endif()
